#!/usr/bin/env bash

projectdir="$1"

[[ -d $projectdir/awklib ]] && {
  # update ass list
  {
    echo '#!/usr/bin/env bash'
    echo
    echo 'awklib() {'
    echo 'if [[ -n ${___dir:-} ]]; then #bashbud'
    echo 'cat "${___dir}/awklib/"*.awk #bashbud'
    echo 'else #bashbud'
    echo "cat << 'EOB'"
    cat "$projectdir/awklib/"*
    echo 'EOB'
    echo 'fi #bashbud'
    echo '}'
  } > "$projectdir/lib/awklib.sh"  
}
